### ISSUE TITLE
[Request] Support for other controllers

### ISSUE THREAD

**Issue by vaguerant** [Laf111/WiiUFtpServer#1]
I've switched over to using your server instead of ftpiiu (the permissions fix makes all the difference for me, thanks for figuring that out), but one feature I really miss is the support for other controllers, added by GaryOderNichts in [their fork](https://github.com/wiiu-controller-mods/ftpiiu-everywhere). In this version, it's possible to exit the app using a Wii Remote, Wii Classic Controller, or Wii U Pro Controller.

I often use my Wii U with the GamePad out of reach in the dock and a Wii Remote on the couch, but while I can launch your server with the Wii Remote, to exit I have to move over to the GamePad just to press one button. It's a minor inconvenience, but avoiding it would make the app much more enjoyable for me and I'm sure at least several others.

**Comment by Laf111** [comment]
2021/05/04 V2-1 : 
    > add a scocket optimization (thanks to V10lator)
    > [**Request] Support for other controllers #1**

**Comment by Laf111** [comment]
Fixed in V2-1.
Tell me if it's not.

**Comment by Laf111** [comment]
memory leaks need to be fixed.
Wiat until the V2-1 release

**Comment by Laf111** [comment]
Please tell me if it is OK now.
Thanks

**Comment by vaguerant** [comment]
Unfortunately, exiting doesn't work at all on my end in V2-1. Even using the GamePad, I can't exit the app. I also tested a solo Wiimote and a Wiimote with Wii Classic Controller attached. None of them works, I have to fully shut off the Wii U to exit WiiUFtpServer.

I am running the HBL version here; unsure whether this issue carries over to the installable title.

**Comment by Laf111** [comment]
Thanks for your feedback.
The gamePad works in channel version.
I reopen the issue.

**Comment by Laf111** [comment]
2021/05/09 V2-2 : 
    > fix regression : can't exit HBL version
      HBL : gamePad, wiiMote +? : OK
      HBC : only gamePad
