### ISSUE TITLE
The WiiUFtpServer app hang when I run.

### ISSUE THREAD

**Issue by nhldp** [Laf111/WiiUFtpServer#12]
The HBL WiiUFtpServer app hang when I run, every time.
I am using Tiramisu,  if I use FTPiiU_Everywhere, never happen hang, all work fine.

Thanks.

**Comment by Laf111** [comment]
Which FTP client are you using ? 
Nothing is displayed on the console log ?

**Comment by nhldp** [comment]
> Which FTP client are you using ? Nothing is displayed on the console log ?

Never run FTP client, just run WiiUFtpServer in WiiU by HBL,  and then need to force power off the console.

**Comment by Laf111** [comment]
Does wiiuFtpSever started ? 
What is displayed ?  you've just got a blanc screen (i should say red) ?
Could you please take a photo or a video ?

**Comment by nhldp** [comment]
> Does wiiuFtpSever started ? What is displayed ? you've just got a blanc screen (i should say red) ? Could you please take a photo or a video ?

Sorry,  I think it's Tiramisu issue. After I updated the tiramisu latest version,  WiiUFtpServer never hang.
Thank you.

**Comment by Laf111** [comment]
OK, glad you solved it !
Have a nice say

**Comment by nhldp** [comment]
> > Does wiiuFtpSever started ? What is displayed ? you've just got a blanc screen (i should say red) ? Could you please take a photo or a video ?
> 
> Sorry, I think it's Tiramisu issue. After I updated the tiramisu latest version, WiiUFtpServer never hang. Thank you.

Update,  I tested again.
I think it's tiramisu compatibility issue,  if I directly run apps by Homebrew launcher channel after bootup, the apps hang. 
If I go into Homebew by Health Manager first,  all apps work fine. 

Have a nice day and keep healthy.
