### ISSUE TITLE
V7.0 corrupts any file you send to the console

### ISSUE THREAD

**Issue by AuroraWright** [Laf111/WiiUFtpServer#2]
Apparently V7.0 is corrupting data in all files you send to the WiiU. The other way around is fine. The previous release is also fine. I'm using forklift as a client on macOS but I'm pretty certain it's a server issue, as 6.2, ftpii everywhere and other switch/3ds servers all work correctly.
To test, just transfer a file and transfer it back and calculate a hash or check in a hex editor or something

**Comment by Laf111** [comment]
Thank you for your feedback.
I'll have a look and i'll take you informed.

**Comment by Laf111** [comment]
2021/12/26 V7-1 :    
    > HOTFIX : fix issue#02 by disabling user buffer's file optimization on upload (it corrupts files)
    > remove the module transferedFiles : all is now done in ftp (more close to the original design)
    > compute approx transfer rate on server side
    > push to 8 simultaneous transferts
