### ISSUE TITLE
Disconnects to ftp server while copying a injected game

### ISSUE THREAD

**Issue by ExpertStatue** [Laf111/WiiUFtpServer#22]

**Comment by ExpertStatue** [comment]
So when a put on one of my injected games to install it just disconnects to the ftp server and it always fails ftp transfer

**Comment by ExpertStatue** [comment]
and im also using filezilla

**Comment by Laf111** [comment]
Hello, 

You're trying to copy a game in sd:\install (to SDcard), is that it ?

Did the FTP server console hang ? 
What is displayed on the gamePad?
Have you got some photos ? 

And could you detail the file uploaded (name and size)
Thanks

**Comment by ExpertStatue** [comment]
Trying to copy to sd install and the file is 2 969 476 332 bytes and it is resident evil 4 and the ftp server just disconnects and stops then starts after a reboot the wii u and it just gives a error that it could not start the transfer

**Comment by ExpertStatue** [comment]
And it's a gamecube game inject from super paper mario eu

**Comment by Laf111** [comment]
What is the size of your SDCard? 
Are u sure there is enough space on it ? 
What is the name of the file ? (to see if there is some unsupported characters in)

Did the transfer failed immediately ? (as soon you submit the transfer)

Do you know exactly the message displayed ? 
It is on client side (filleZilla) or on the server side (gamepad) ?

**Comment by ExpertStatue** [comment]
my sd is 25 gb sorry i have been busy but the messege was disconnected from server and the game was 700 mb i had 15 gb free at the time

**Comment by ExpertStatue** [comment]
and it did not fail immediately

**Comment by ExpertStatue** [comment]
i tried to gamecube injects re4 and a 750 mb game and i had enough space

**Comment by Laf111** [comment]
I hope that is fixed in V12
