### ISSUE TITLE
Crash when trying to access a folder on SD

### ISSUE THREAD

**Issue by Xpl0itU** [Laf111/WiiUFtpServer#23]
The folder itself had a lot of files, it was a savemii backup of botw, my ftp client shows recv connection reset and then wiiuftpserver crashes, I’ve attached the log so you can take a look at it, might be a libfat issue, but seems unlikely

[2.log](https://github.com/Laf111/WiiUFtpServer/files/8797711/2.log)

**Comment by Laf111** [comment]
Hey, 

In order to reproduce the bug : how many files are in this folder ? 
You confirm that there is no files named with "exotic" characters in ? 

Thanks

**Comment by Xpl0itU** [comment]
It has a file and a folder
![42F6D6F2-39BE-4170-94DD-E70B4E2B2D24](https://user-images.githubusercontent.com/24777100/171145139-080706f5-e344-48ef-8bc7-fc4f90bde66b.png)
No exotic characters or anything, it opens just fine on ftpiiu everywhere, so you must’ve broken something

**Comment by Laf111** [comment]
I hope that is fixed in V12
