### ISSUE TITLE
unstable on tiramisu

### ISSUE THREAD

**Issue by taneofpain** [Laf111/WiiUFtpServer#24]
launches fine, can connect, login and start transferring however crashes during transfers and hard locks the system quite quickly.

**Comment by Laf111** [comment]
Unfortunately, it seems that is not only for Tiramisu.
I think it comes from the WUT library...

I currently trying to make a version using dynamic_libs instead of WUT.

**Comment by Laf111** [comment]
I hope that is fixed in V12
