### ISSUE TITLE
Aroma wuhb build?

### ISSUE THREAD

**Issue by amberdambey** [Laf111/WiiUFtpServer#29]
Is it possible to compile this as a WUHB file for use with Aroma, similar to the channel version? I can understand if it's difficult to port ELF (non-RPX) homebrew to WUHB.

**Comment by Laf111** [comment]
Unfortunatelty, RPX and WUHB build need WUT library and it leads in CRC errors and stability issues...

I've tried to replace FAT+libIOSUHAX with MOCHA but it seems that the issue in on wut_devopt_tab.

Maybe, i'll release a version where simultaneous uploads numbers (at least on SD card) will be limited to one....

**Comment by Laf111** [comment]
Hum... same using MOCHA (CRC errors and stability issues with sdcard)
I'm pretty sure that the issue is in wut_devopt_tab

**Comment by Laf111** [comment]
Transferring feedback to Aroma plugin : https://github.com/Laf111/ftpiiu_plugin
