### ISSUE TITLE
Error when CWD to / storage_usb

### ISSUE THREAD

**Issue by Exorcism0666** [Laf111/WiiUFtpServer#9]
I don't really know how to describe this "bug" except that I can't access the USB key from the file (; v ;)
![image](https://user-images.githubusercontent.com/46537034/151712645-d1271994-aaf8-4798-b86b-4f3b36bec8ef.png)

**Comment by Laf111** [comment]
Sorry, can't reproduce this issue.
Are you sure that your USB device is OK ? 
Didi you ever use it on the wii-u ? (i.e formated in FAT32 with 32K clusters ?)

**Comment by Exorcism0666** [comment]
Yes, my USB key was well formatted in FAT32 with 32kil of cluster, I had plugged it into the front of the Wii U.
